Fix/drawer boolean values
SoftwareBrothers/adminjs pull request #1269
Opened 2022-10-06 06:24 UTC by jwasiak

2022-10-06 06:43 UTC, dziraf requested changes

2022-10-06 06:43 UTC, dziraf commented on src/frontend/components/property-type/reference/filter.tsx
> +  async loadOptions(inputValue: string): Promise<Array<{value: string | number; label: string }>> {
`Array<SelectRecord>`>

2022-10-06 09:22 UTC, jwasiak commented on src/frontend/components/property-type/reference/filter.tsx
> +  async loadOptions(inputValue: string): Promise<Array<{value: string | number; label: string }>> {
fixed

2022-10-07 11:41 UTC, dziraf commented
@jwasiak there are conflicts with `master` branch

2022-11-04 11:06 UTC, closed without merging