feat: include currentAdmin when calling adapter functions
SoftwareBrothers/adminjs pull request #1357
Opened 2022-12-27 05:57 UTC by AshotN

Closes #1353

Is backwards compatible, adapters do not need to use `currentAdmin` if they don't need it

2023-01-04 09:42 UTC, dziraf commented
@AshotN How about we just pass `context` as the last argument? This way you'd be able to access even more action/request scoped details.

2023-01-04 16:48 UTC, AshotN commented
That sounds good, I'll edit the PR

2023-01-05 04:48 UTC, AshotN commented
I had not originally noticed that AdminJS itself relies on a lot of the adapter functions, so those need to pass the context as well. I made the changes, but the tests are failing and I'm not sure how to fix them. Would like some help on that front

2023-01-05 21:27 UTC, dziraf commented
The tests aren't failing but there are some type errors.

We could try to type it as `context?: Partial<ActionContext> = {}`. It should make the third argument optional but it will be up to adapter's authors to make sure that `context.currentAdmin` or other attributes are available. This shouldn't break anything since none of current adapters use `context`.

2023-01-06 05:06 UTC, AshotN commented
Ya I just realized that without having context as optional, current adapters will type-error. I will make it optional again

2023-01-12 21:00 UTC, AshotN commented
@dziraf Changed back to optional, please review and let me know if it seems ok to you.

2023-01-13 08:30 UTC, dziraf requested changes
@AshotN Do you think this is ready to be merged otherwise?

2023-01-13 08:30 UTC, dziraf commented on src/backend/adapters/record/base-record.ts
>     * @param  {ActionContext}           context
`context` -> `[context]`

This should make jsdoc treat context as optional.

2023-01-13 22:00 UTC, AshotN commented
I believe so. I don't see any glaring issues but I will test it with my adapter again.

2023-01-14 02:51 UTC, AshotN commented
@dziraf I think this is good to go

2023-01-17 09:14 UTC, dziraf approved these changes
This looks good to me, worst case scenario we will revert it.

2023-01-17 09:15 UTC, merged